@main
struct SensoriumCoreTestRunner {
    static func main() {
        let tests: [(String, () -> Void)] = [
            ("hello message round-trips through versioned frame", testHelloMessageRoundTripsThroughVersionedFrame),
            ("canvas control messages round-trip through versioned frame", testCanvasControlMessagesRoundTripThroughVersionedFrame),
            ("canvas request and ready surfaceID round-trips when present or absent", testCanvasRequestAndReadySurfaceIDRoundTripWhenPresentOrAbsent),
            ("canvas ready hostName round-trips when present or absent", testCanvasReadyHostNameRoundTripsWhenPresentOrAbsent),
            ("canvas control messages stay wire-compatible across surfaceID", testCanvasControlMessagesStayWireCompatibleAcrossSurfaceID),
            ("authenticated hello round-trips and verifies", testAuthenticatedHelloRoundTripsAndVerifies),
            ("encoded video frame packet round-trips and bounds payload", testEncodedVideoFramePacketRoundTripsAndBoundsPayload),
            ("encoded video frame refuses a presentation time past Int64.max", testEncodedVideoFrameRefusesAPresentationTimePastInt64Max),
            ("tagged transport packet demultiplexes control and video", testTaggedTransportPacketDemultiplexesControlAndVideo),
            ("tag-2 video-for-surface round-trips and matches tag 1's payload", testTag2VideoForSurfaceRoundTripsAndMatchesTag1Payload),
            ("tag-2 rejects an out-of-range surfaceID and a too-short payload", testTag2RejectsSurfaceIDOutsideCapAndTooShortPayload),
            ("tag-2 encodes and decodes at the maximum frame size", testTag2EncodesAndDecodesAtMaximumFrameSize),
            ("an unrecognized transport tag is skippable, not fatal", testUnrecognizedTransportTagIsSkippableNotFatal),
            ("malformed transport frames are still fatal", testMalformedTransportFramesAreStillFatal),
            ("an unrecognized control message type is skippable, not fatal", testUnrecognizedMessageTypeIsSkippableNotFatal),
            ("malformed (non-JSON) control payloads still throw", testMalformedControlJSONStillThrows),
            ("H.264 codec configuration round-trips parameter sets", testH264CodecConfigurationRoundTripsParameterSets),
            ("malformed frames are rejected", testMalformedFramesAreRejected),
            ("pairing code expires and cannot be reused", testPairingCodeExpiresAndCannotBeReused),
            ("a pairing code's failure budget bounds guessing and the comparison is constant time", testPairingCodeBudgetBoundsGuessesAndComparesInConstantTime),
            ("device identity signs and verifies handshake transcript", testDeviceIdentitySignsAndVerifiesHandshakeTranscript),
            ("input events round-trip through versioned frame", testInputEventsRoundTripThroughVersionedFrame),
            ("input sequence and inputApplied round-trip and an unrecognized message decodes safely", testInputSequenceAndInputAppliedRoundTripAndUnrecognizedDecodesSafely),
            ("input and viewerDrawableSize surfaceID round-trips when present or absent", testInputAndViewerDrawableSizeSurfaceIDRoundTripWhenPresentOrAbsent),
            ("canvas ready transcript covers surfaceID and tampering fails verification", testCanvasReadyTranscriptCoversSurfaceIDAndTamperingFailsVerification),
            ("reconnect backoff doubles and is capped", testReconnectBackoffDoublesAndIsCapped),
            ("connection supervisor retries loss and stops on user disconnect", testConnectionSupervisorRetriesLossAndStopsOnUserDisconnect),
            ("connection supervisor gives up after maximum attempts", testConnectionSupervisorGivesUpAfterMaximumAttempts),
            ("latency statistics compute percentiles and reject bad samples", testLatencyStatisticsComputePercentilesAndRejectBadSamples),
            ("latency samples are bounded and evict the oldest", testLatencySamplesAreBoundedAndEvictTheOldest),
            ("stage metrics reject out-of-order timestamps", testStageMetricsRejectOutOfOrderTimestamps),
            ("pairing messages round-trip through versioned frame", testPairingMessagesRoundTripThroughVersionedFrame),
            ("file identity store persists and is owner-only", testFileIdentityStorePersistsAndIsOwnerOnly),
            ("a corrupt device identity file is refused, not replaced", testFileDeviceIdentityStoreRefusesACorruptFileRatherThanReplacingIt),
            ("identity stores tighten their directory and leave no temporary file", testFileIdentityStoresTightenTheirDirectoryAndLeaveNoTemporaryFile),
            ("identity stores replace a key with a fresh one", testFileIdentityStoresReplaceWithAFreshKey),
            ("media flow monitor reports rates and silence", testMediaFlowMonitorReportsRatesAndSilence),
            ("host TLS identity generates a parseable certificate and pin", testHostTLSIdentityGeneratesParseableCertificateAndPin),
            ("file TLS identity persists certificate pin and private key", testFileHostTLSIdentityStorePersistsCertificatePinAndPrivateKey),
            ("an invalid stored TLS value is refused", testFileHostTLSIdentityStoreRefusesAnInvalidStoredValue),
            ("clock offset estimator prefers the lowest round trip sample", testClockOffsetEstimatorPrefersTheLowestRoundTripSample),
            ("time sync messages round-trip through versioned frame", testTimeSyncMessagesRoundTripThroughVersionedFrame),
            ("session latency recorder needs clock sync before reporting end-to-end", testSessionLatencyRecorderNeedsClockSyncBeforeReportingEndToEnd),
            ("latency trace writer appends one JSON line for each stage", testLatencyTraceWriterAppendsOneJSONLineForEachStage),
            ("session latency recorder records input round trip and it appears in the trace", testSessionLatencyRecorderRecordsInputRoundTripAndItAppearsInTheTrace),
            ("monotonic clock only moves forward", testMonotonicClockOnlyMovesForward),
            ("clock synchronizer accepts only replies to requests it sent", testClockSynchronizerAcceptsOnlyRepliesToRequestsItSent),
            ("Sensorium entry URL accepts only the canonical enter form", testSensoriumEntryURLAcceptsOnlyCanonicalEnterURL),
            ("test pattern phase bounces inside the canvas and never leaves it", testTestPatternPhaseBouncesInsideTheCanvasAndNeverLeavesIt),
            ("stream scale follows the viewer drawable within the canvas native limit", testStreamScaleFollowsViewerDrawableWithinCanvasNativeLimit),
            ("encode sustainability policy withholds a verdict until there are real samples", testEncodeSustainabilityPolicyWithholdsAVerdictUntilThereAreRealSamples),
            ("viewer drawable size carries a user scale cap and validates it like its dimensions", testViewerDrawableSizeCarriesAUserScaleCapAndValidatesItLikeItsDimensions),
            ("viewer drawable size round-trips and refuses degenerate values", testViewerDrawableSizeRoundTripsAndRefusesDegenerateValues),
            ("viewer focus round-trips every state and is ignorable by an old peer", testViewerFocusRoundTripsEveryStateAndIsIgnorableByAnOldPeer),
            ("telemetry round-trips per surface and is ignorable by an old peer", testTelemetryRoundTripsPerSurfaceAndIsIgnorableByAnOldPeer),
            ("telemetry carries the applied scale and the learned ceiling", testTelemetryCarriesTheAppliedScaleAndTheLearnedCeiling),
            ("viewer telemetry round-trips and is skippable by an old host", testViewerTelemetryRoundTripsAndIsSkippableByAnOldHost),
            ("telemetry carries the applied frame rate, quality and limit reason", testTelemetryCarriesTheAppliedFrameRateQualityAndLimit),
            ("the viewer telemetry store forgets a reading that stopped arriving", testViewerTelemetryStoreForgetsAReadingThatStoppedArriving),
            ("the viewer telemetry store refuses impossible numbers", testViewerTelemetryStoreRefusesImpossibleNumbers),
            ("clipboard text and images round-trip through transport tag 3", testClipboardTextAndImageRoundTripThroughTransport),
            ("an oversize clipboard is refused cleanly on send and receive", testOversizeClipboardIsRefusedCleanlyOnBothSendAndReceive),
            ("applying a received clipboard is never sent back", testApplyingAReceivedClipboardIsNeverSentBack),
            ("concealed or transient clipboard content is never sent", testConcealedOrTransientClipboardIsNeverSent),
            ("disabled clipboard sync neither sends nor applies", testDisabledClipboardSyncNeitherSendsNorApplies),
            ("clipboard sharing defaults to off, and an engine built with it neither polls nor applies", testClipboardSharingDefaultsToOffAndAnEngineBuiltWithItNeitherPollsNorApplies),
            ("clipboard sync's live enable/disable toggle accounts for the change-count baseline in both directions", testClipboardSyncEnabledToggleAccountsChangesAcrossBothDirections),
            ("clipboard descriptions carry sizes and outcomes only", testClipboardDescriptionsCarrySizesAndOutcomesOnly),
            ("a clipboard frame is skippable by a peer that predates it", testAClipboardFrameIsSkippableByAPeerThatPredatesIt),
            ("malformed clipboard payloads are rejected", testMalformedClipboardPayloadsAreRejected),
            ("transport frames decode from a slice that does not start at zero", testTransportFramesDecodeFromASliceThatDoesNotStartAtZero),
            ("any pasteboard item carrying an excluded type refuses the whole pasteboard", testAnyPasteboardItemCarryingAnExcludedTypeRefusesTheWholePasteboard),
            ("tailnet directory parses tolerantly and sorts for the picker", testTailnetDirectoryParsesAndSortsPeers),
            ("a tailnet peer's dial address prefers IPv4, then the MagicDNS name, then IPv6", testTailnetPeerDialAddressPrefersIPv4ThenMagicDNSNameThenIPv6),
            ("stream scale preference composes with the sustainability ceiling", testStreamScalePreferenceComposesWithTheSustainabilityCeiling),
            ("host-screen types: geometry round-trips and a capture intent is never silently substituted", testHostScreenTypes),
            ("host-screen protocol round-trips, skips on an older peer, and can only reference an arming", testHostScreenProtocol),
            ("host-screen display mode messages round-trip, refuse malformed fields, and stay skippable for an older peer", testHostScreenModeProtocol),
            ("stream scale preference message round-trips both directions", testStreamScalePreferenceMessageRoundTripsBothDirections),
            ("a malformed stream scale preference refuses as malformed", testStreamScalePreferenceMessageMalformedRefusesAsMalformed),
            ("an off-quantum or out-of-range fixed value is not rejected at the wire", testStreamScalePreferenceMessageDoesNotRejectOffQuantumOrOutOfRangeValues),
            ("a stream scale preference drops unknown extra fields", testStreamScalePreferenceMessageDropsUnknownExtraFields),
            ("telemetry carries a clamped user choice", testTelemetryCarriesClampedFromUserChoice),
            ("displayCount round-trips 1 and 2", testDisplayCountRoundTripsOneAndTwo),
            ("displayCount refuses anything outside 1 or 2", testDisplayCountRefusesAnythingOutsideOneOrTwo),
            ("displayCount drops unknown extra fields", testDisplayCountDropsUnknownExtraFields),
            ("pairRequest presence-credential registration round-trips, tolerates absence, and refuses malformed strength or partial fields", testPairRequestPresenceCredentialRegistration),
            ("pairRequest proof of possession round-trips and binds every field it covers", testPairRequestSignatureRoundTripsAndBindsEveryFieldItCovers),
            ("pairIntent round-trips its device name and refuses a missing or empty one as malformed", testPairIntentRoundTripsAndRefusesMalformed),
            ("scale range is general, and the session canvas range reproduces today's constants", testScaleRangeIsGeneralAndTheSessionCanvasRangeReproducesTodaysConstants),
            ("clipboardSharing round-trips both values and refuses malformed shapes", testClipboardSharingRoundTripsAndRefusesMalformed),
            ("the fidelity ladder spends resolution before frame rate and quality", testStreamFidelityLadderSpendsResolutionBeforeFrameRateAndQuality),
            ("fidelity pressure names the stage that cannot keep up", testStreamFidelityPressureNamesTheStageThatCannotKeepUp),
            ("fidelity pressure prefers the earliest stage that is behind", testStreamFidelityPressurePrefersTheEarliestStageThatIsBehind),
            ("fidelity steps down after one pressured tick and back up after two", testStreamFidelityStepsDownAfterOnePressuredTickAndBackUpAfterTwo),
            ("fidelity applies at most one change every two seconds", testStreamFidelityAppliesAtMostOneChangeEveryTwoSeconds),
            ("fidelity lifts quality on a still screen and asks for a key frame", testStreamFidelityLiftsQualityOnAStillScreenAndAsksForAKeyFrame),
            ("fidelity gives back what a still screen bought when it moves again", testStreamFidelityGivesBackWhatAStillScreenBoughtWhenItMovesAgain),
            ("fidelity refreshes the still picture again after a rebuild", testStreamFidelityRefreshesTheStillPictureAgainAfterARebuild),
            ("fidelity holds off a lever a probe failed into for longer each time", testStreamFidelityHoldsOffALeverAProbeFailedIntoForLongerEachTime),
            ("cleared fidelity ceilings reopen a lever and forget its hold-off", testStreamFidelityClearedCeilingsReopenALeverAndForgetItsHoldOff),
            ("fidelity lowers quality first for a link and needs viewer evidence to raise it", testStreamFidelityLowersQualityFirstForALinkAndNeedsViewerEvidenceToRaiseIt),
            ("fidelity ignores the opening burst and the one after every rebuild", testStreamFidelityIgnoresTheOpeningBurstAndTheOneAfterEveryRebuild),
            ("fidelity replays the recorded Wi-Fi run and settles one step down", testStreamFidelityReplaysTheRecordedWiFiRunAndSettlesOneStepDown),
            ("fidelity will not climb back into a frame rate the encoder cannot afford", testStreamFidelityWillNotClimbBackIntoAFrameRateTheEncoderCannotAfford),
            ("fidelity chooses the resolution that holds sixty frames a second", testStreamFidelityChoosesTheResolutionThatHoldsSixtyFramesASecond),
            ("fidelity reads every drop counter as this tick's own", testStreamFidelityReadsEveryDropCounterAsThisTicksOwn),
            ("fidelity refreshes the still picture once per still period", testStreamFidelityRefreshesTheStillPictureOncePerStillPeriod),
            ("fidelity takes the frame rate back on a still screen", testStreamFidelityTakesTheFrameRateBackOnAStillScreen),
            ("fidelity judges the link on what was sent rather than what was encoded", testStreamFidelityJudgesTheLinkOnWhatWasSentRatherThanWhatWasEncoded),
            ("fidelity holds off a lever that fails after its probation", testStreamFidelityHoldsOffALeverThatFailsAfterItsProbation),
            ("fidelity pressure judges the encoder against the screen's own capture rate", testStreamFidelityEncoderPressureJudgesAgainstTheScreensOwnCaptureRate),
            ("fidelity climbs back into a frame rate the quiet screen makes affordable", testStreamFidelityClimbsBackIntoAFrameRateTheQuietScreenMakesAffordable),
            ("fidelity holds the requested scale on a quiet coding screen", testStreamFidelityHoldsTheRequestedScaleOnAQuietCodingScreen),
            ("fidelity spends resolution before the frame rate and quality", testStreamFidelitySpendsResolutionBeforeTheFrameRateAndQuality),
            ("fidelity gives resolution up to what the link can carry", testStreamFidelityGivesResolutionUpToWhatTheLinkCanCarry),
            ("fidelity lets a quiet screen back to the scale its bits fit", testStreamFidelityLetsAQuietScreenBackToTheScaleItsBitsFit),
            ("fidelity holds off a resolution the rebuild refused", testStreamFidelityHoldsOffAResolutionTheRebuildRefused)
        ]

        for (name, test) in tests {
            test()
            print("PASS: \(name)")
        }

        print("PASS: \(tests.count) tests")
    }
}
